services:
  - type: web
    name: snow-brothers
    env: node
    buildCommand: npm install && npm run build
    startCommand: NODE_ENV=production node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
