services:
  - type: web
    name: snow-brothers
    env: node
    buildCommand: rm -rf node_modules && npm install --include=dev && npm run build
    startCommand: NODE_ENV=production node server/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: "false"
